Repository ArkEcosystem/elixir-crypto, pull requests merged in 2019-05, with the labels that each got.

#40 chore: update contribution link
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#41 feat: support new vendorfield length
  lib/arkecosystem/crypto/transactions/transaction.ex
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#43 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task
